language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew install xctool
script:
  - xctool -workspace Sokol.xcworkspace -scheme Sokol -sdk iphonesimulator
  - xctool -workspace Sokol.xcworkspace -scheme SokolTests -sdk iphonesimulator
